name: Проверка репозитория
on: [push]
jobs:
  tests:
    name: Тесты скриптов
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Тест создания файла
      run: |
        chmod +x test_creator.sh
        ./test_creator.sh
    - name: Тест удаления файла
      run: |
        chmod +x test_remover.sh
        ./test_remover.sh
    - name: Тест чтения в скрипте и вывода скрипта
      run: |
        chmod +x test_script.sh
        ./test_script.sh
    - name: Тест сумматора
      run: |
        chmod +x test_summator.sh
        ./test_summator.sh
